### ISSUE TITLE
Lazy primes implementations are wrong

### ISSUE THREAD

**Issue by rmanne** [timmyjose/timmyjose.github.io#23]
2020-09-16-lazy-primes-in-idris.md

The output in the implementations have '9' and '15' etc, which are not prime numbers. sieve should be recursive:

    sieve (p : xs) = p : sieve (filter (\x -> x `mod` p /= 0) xs)

I'm not sure how this affects the relative performances between the two languages, but 1000000 was definitely too much for my laptop, 10000 itself took 2 seconds in haskell.

**Comment by timmyjose** [comment]
You're absolutely right, of course. This is what happens when one posts stuff a bit toolate at night! :D ... thank you again for catching the embarrassing mistake quickly!

**Comment by timmyjose** [comment]
Closed with fix in PR: https://github.com/timmyjose/timmyjose.github.io/pull/24
